services:
  pdfengine:
    build: ./engine/
    container_name: pdfengine
    restart: always
    ports:
      - "3000:3000"
    environment:
      - TZ=Europe/Rome
    networks:
      - pdfmerge
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 10s
      timeout: 5s
      retries: 5

  fronter:
    build: ./stream/
    container_name: stream-merger
    restart: always
    ports:
      - "80:80"
    depends_on:
      pdfengine:
        condition: service_healthy
    environment:
      - TZ=Europe/Rome
    networks:
      - pdfmerge

networks:
  pdfmerge:
    driver: bridge
